some_image = Image("image1.png");
first_sprite = Sprite(some_image);

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

first_sprite.SetY(screen_height / 2 - some_image.GetHeight() / 2);
first_sprite.SetX(screen_width / 2 - some_image.GetWidth() / 2);

current_image = 1;
time_count = 0;

fun refresh_callback() {
    time_count++;
    
    if (time_count >= 100) {
        time_count = 0;
        
        if (current_image >= 2) {
            current_image = 1;
        } else {
            current_image = current_image + 1;
        }
        
        change = Image("image" + current_image + ".png");
        first_sprite.SetImage(change);
    }
}

Window.SetBackgroundTopColor(0, 0, 0);           
Window.SetBackgroundBottomColor(0, 0, 0);

Plymouth.SetRefreshFunction(refresh_callback);
